name: pyopencap
channels:
   - anaconda
   - conda-forge
dependencies:
   - eigen
   - hdf5
   - cmake
   - numpy
   - gcc_linux-64
   - pip:
      - docutils==0.16
      - sphinx-rtd-theme
      - sphinx
